[font]
size = 12

[font.bold]
family = "JetBrainsMono Nerd Font Mono"

[font.italic]
family = "JetBrainsMono Nerd Font Mono"

[font.normal]
family = "JetBrainsMono Nerd Font Mono"

[window]
# full / none
decorations = "none"
dynamic_padding = false
opacity = 0.75

[window.dimensions]
columns = 120
lines = 30

[window.padding]
x = 15
y = 10
